# Generated by Django 4.1.3 on 2023-01-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('cedula', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=90)),
                ('correo', models.CharField(max_length=90)),
            ],
        ),
    ]
